#!/usr/bin/env bash

what=./data/N3-5-5-2-2.nc4
#wchg=127

for mode in 0 1 2 12 13 14 20 29 30; do
  for (( seed = 0 ; seed < 20 ; seed++ )); do

    if [ -z "$wchg" ]; then
      printf "[$what $seed $mode]: "
    else
      printf "[$what $seed $mode $wchg]: "
    fi

    ./MCFBlock_test $what $seed $mode $wchg

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

  done
done
