#!/usr/bin/env bash

#wchg=127
#rounds=40

#for mode in 0 1 2 12 13 14 20 29 30
for mode in 16; do
  for type in net goto; do
    for (( seed = 0 ; seed < 3 ; seed++ )); do

      #for sz in 8_8 8_32 10_8 10_64 12_8 14_8
      for sz in 8_8 8_32 10_8 10_64 12_8; do
        for h in 1 2 3 4 5; do

          what=../data/nc4/${type}${sz}_${h}.nc4
          if [ -z "$wchg" ]; then
            printf "[$what $seed $mode]: "
          else
            if [ -z "$rounds" ]; then
              printf "[$what $seed $mode $wchg]: "
            else
              printf "[$what $seed $mode $wchg $rounds]: "
            fi
          fi

          ./MCFBlock_test $what $seed $mode $wchg $rounds

          retVal=$?
          if [ $retVal -ne 0 ]; then
            exit 1
          fi

        done # h
      done   # sz
    done     # seed
  done       # type
done         # mode
